// Jenkinsfile for NationalParks
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-slave-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
) {
  node('skopeo-pod') {
    echo "GUID: ${GUID}"
    echo "CLUSTER: ${CLUSTER}"

    // Your Pipeline Code goes here. Make sure to use the ${GUID} and ${CLUSTER} parameters where appropriate
    // You need to build the application in directory `Nationalparks`.
    // Also copy "../nexus_settings.xml" to your build directory
    // and replace 'GUID' in the file with your ${GUID} to point to >your< Nexus instance

    def mvnCmd = "mvn -s ./nexus_settings.xml"


    // Checkout Source Code
    stage('Checkout Source') {
      checkout scm
    }

    dir('Nationalparks'){

      // Extract version and other properties from the pom.xml
      def groupId    = getGroupIdFromPom("pom.xml")
      def artifactId = getArtifactIdFromPom("pom.xml")
      def version    = getVersionFromPom("pom.xml")

      // Set the tag for the development image: version + build number
      def devTag  = "${version}-${env.BUILD_NUMBER}"
      // Set the tag for the production image: version
      def prodTag = version

      sh 'cp ../nexus_settings.xml .'
      sh "sed -i 's/GUID/'${GUID}'/g' ./nexus_settings.xml"

      stage('Build Code Artifacts') {
        echo "Building version ${version}"
        sh "${mvnCmd} clean install -DskipTests=true"
      }

      
      // Using Maven run the unit tests
      stage('Unit Tests') {
        echo "Running Unit Tests"
        sh "${mvnCmd} test"
      }
              
      // Using Maven call SonarQube for Code Analysis
      stage('Code Analysis') {
          echo "Running Code Analysis"
          sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube-${GUID}-sonarqube.apps.${CLUSTER} -Dsonar.projectVersion=${devTag}"      
      }
        
      
      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        echo "Publish to Nexus"
        sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3-${GUID}-nexus.apps.${CLUSTER}/repository/releases"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image nationalparks:${devTag}"
        sh "oc start-build nationalparks --follow=true --from-file=http://nexus3-${GUID}-nexus.apps.${CLUSTER}/repository/releases/com/openshift/evg/roadshow/nationalparks/${version}/nationalparks-${version}.jar -n ${GUID}-parks-dev"
        openshiftVerifyBuild bldCfg: 'nationalparks', checkForTriggeredDeployments: 'false', namespace: '${GUID}-parks-dev', verbose: 'false'
        openshiftTag alias: 'false', destStream: 'nationalparks', destTag: devTag, destinationNamespace: '${GUID}-parks-dev', namespace: '${GUID}-parks-dev', srcStream: 'nationalparks', srcTag: 'latest', verbose: 'false'
      }

      stage('Deploy to Dev') {
        echo "Deploying nationalparks image to Development Project"
        sh "oc set image dc/nationalparks nationalparks=docker-registry.default.svc:5000/${GUID}-parks-dev/nationalparks:${devTag} -n ${GUID}-parks-dev"
        openshiftDeploy depCfg: 'nationalparks', namespace: '${GUID}-parks-dev', verbose: 'false'
        openshiftVerifyDeployment depCfg: 'nationalparks', namespace: '${GUID}-parks-dev', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true'
        openshiftVerifyService namespace: '${GUID}-parks-dev', svcName: 'nationalparks', verbose: 'false'

      }

      // Run Integration Tests in the Development Environment.
      stage('Integration Tests') {
        echo "Running Integration Tests"
        sleep 20
        sh "curl -i -X GET http://nationalparks.${GUID}-parks-dev.svc.cluster.local:8080/ws/info/"

      }

      // Copy Image to Nexus Docker Registry
      stage('Copy Image to Nexus Docker Registry') {
        echo "Copy image to Nexus Docker Registry"
        sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:admin123 docker://docker-registry.default.svc.cluster.local:5000/${GUID}-parks-dev/nationalparks:${devTag} docker://nexus-registry.${GUID}-nexus.svc.cluster.local:5000/nationalparks:${devTag}"

        // Tag the built image with the production tag.
        openshiftTag alias: 'false', destStream: 'nationalparks', destTag: prodTag, destinationNamespace: '${GUID}-parks-dev', namespace: '${GUID}-parks-dev', srcStream: 'nationalparks', srcTag: devTag, verbose: 'false'
      }

      /////////////////////////////////

      // Blue/Green Deployment into Production
      // -------------------------------------
      def destApp   = ""
      def activeApp = ""

      stage('Blue/Green Production Deployment') {
        //activeApp = sh(returnStdout: true, script: "oc get route nationalparks -n ${GUID}-parks-prod -o jsonpath='{ .spec.to.name }'").trim()
        activeApp = sh(returnStdout: true, script: "oc get svc -l type=parksmap-backend,app=nationalparks -o jsonpath='{ .items[0].metadata.name }' -n ${GUID}-parks-prod").trim()
        if (activeApp == "nationalparks-green") {
          destApp = "nationalparks-blue"
        } else {
          destApp = "nationalparks-green"
        }
        echo "Active Application:      " + activeApp
        echo "Destination Application: " + destApp

        // Update the Image on the Production Deployment Config
        sh "oc set image dc/${destApp} ${destApp}=docker-registry.default.svc:5000/${GUID}-parks-dev/nationalparks:${prodTag} -n ${GUID}-parks-prod"

        // Deploy the inactive application.
        openshiftDeploy depCfg: destApp, namespace: '${GUID}-parks-prod', verbose: 'false'
        openshiftVerifyDeployment depCfg: destApp, namespace: '${GUID}-parks-prod', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true'
        openshiftVerifyService namespace: '${GUID}-parks-prod', svcName: destApp, verbose: 'false'
      }

      stage('Switch over to new Version') {
        echo "Switching Production application to ${destApp}."

        //Need to remove services to re-trigger parksmap to read changes

        // Remove label from active service
        //sh 'oc delete svc/' + activeApp + ' -n ${GUID}-parks-prod'
        //sh 'oc expose dc/' + activeApp + ' -l app=nationalparks -n ${GUID}-parks-prod --port 8080'
        sh 'oc label svc/' + activeApp + ' type- -n ${GUID}-parks-prod'


        // Add label to destination service
        //sh 'oc delete svc/' + destApp + ' -n ${GUID}-parks-prod'
        //sh 'oc expose dc/' + destApp + ' -l app=nationalparks,type=parksmap-backend -n ${GUID}-parks-prod --port 8080'

        sh 'oc label svc/' + destApp + ' type=parksmap-backend -n ${GUID}-parks-prod'
        sh 'oc label svc/' + destApp + ' app=nationalparks --overwrite -n ${GUID}-parks-prod'

      }


    }



    

 
  }
}



// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
